// File generated by FlutterFire CLI.
// TODO: This is a placeholder. Run `flutterfire configure` from the
// `classconnect_app/` directory (after creating a Firebase project) to
// overwrite this file with real platform configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured yet. '
        'Run `flutterfire configure` from the classconnect_app directory.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured yet. '
          'Run `flutterfire configure` from the classconnect_app directory.',
        );
    }
  }
}
